version: '3.8'

services:
  # Container do Symfony (backend)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_app
    environment:
      - DATABASE_URL=mysql://root:secret@database:3306/intelia_docker?serverVersion=5.7
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - database

  # Container do Vue.js (frontend)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    volumes:
      - ./frontend:/app:rw
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

  # Container do banco de dados MySQL
  database:
    image: mysql:5.7
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: intelia_docker
      MYSQL_USER: intelia
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: